# Synced from the LogTriage service (https://logtriage.app). Edits made here are
# overwritten on the next sync; see 'Contributing' in README.md.
"""
Kubernetes API Server Audit Log parser.

Input: NDJSON (one audit event per line) or JSON array.
Generated by the Kubernetes API server with audit policy enabled.

Reference: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/

Key fields mapped:
  requestReceivedTimestamp / stageTimestamp → timestamp
  sourceIPs[0]               → ip_address
  userAgent                  → user_agent
  verb                       → http_method (get→GET, create→POST, delete→DELETE, etc.)
  objectRef.resource + namespace → path
  responseStatus.code        → status_code
  user.username              → user_principal_name
  annotations["authorization.k8s.io/decision"] → failure_reason if "forbid"
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any

from logtriage.parsers.base_parser import BaseParser
from logtriage.models import LogEvent, LogFormat

logger = logging.getLogger(__name__)

_VERB_METHOD: dict[str, str] = {
    "get": "GET",
    "list": "GET",
    "watch": "GET",
    "create": "POST",
    "update": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "deletecollection": "DELETE",
    "exec": "POST",
    "portforward": "POST",
    "proxy": "GET",
    "connect": "CONNECT",
    "bind": "POST",
    "escalate": "POST",
    "impersonate": "POST",
}

# Subresources that indicate high-risk activity
_HIGH_RISK_SUBRESOURCES = {"exec", "portforward", "attach", "log", "proxy"}

# Resources that are sensitive
_SENSITIVE_RESOURCES = {
    "secrets", "serviceaccounts", "clusterrolebindings", "rolebindings",
    "clusterroles", "roles", "tokenreviews", "subjectaccessreviews",
}


def _ts(raw: str | None) -> datetime:
    if not raw:
        return datetime.now(timezone.utc)
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return datetime.now(timezone.utc)


def _build_path(obj_ref: dict[str, Any] | None, verb: str | None, subresource: str | None) -> str:
    if not obj_ref:
        return f"/k8s/{verb or 'unknown'}"
    ns = obj_ref.get("namespace", "")
    resource = obj_ref.get("resource", "unknown")
    name = obj_ref.get("name", "")
    parts = ["/k8s"]
    if ns:
        parts += ["namespaces", ns]
    parts.append(resource)
    if name:
        parts.append(name)
    if subresource:
        parts.append(subresource)
    return "/".join(parts)


def _parse_event(raw: dict[str, Any]) -> LogEvent | None:
    try:
        verb: str | None = raw.get("verb")
        obj_ref: dict[str, Any] | None = raw.get("objectRef")
        user: dict[str, Any] = raw.get("user") or {}
        source_ips: list[str] = raw.get("sourceIPs") or []
        response: dict[str, Any] = raw.get("responseStatus") or {}
        annotations: dict[str, str] = raw.get("annotations") or {}
        subresource: str | None = obj_ref.get("subresource") if obj_ref else None

        ts_raw = raw.get("requestReceivedTimestamp") or raw.get("stageTimestamp")
        status_code: int | None = response.get("code")

        # Forbidden by RBAC
        authz_decision = annotations.get("authorization.k8s.io/decision", "")
        failure_reason = None
        if authz_decision == "forbid":
            failure_reason = "RBAC: access forbidden"
            if not status_code:
                status_code = 403
        elif status_code and status_code >= 400:
            failure_reason = response.get("message") or response.get("reason")

        username = user.get("username")
        if not username:
            username = user.get("extra", {}).get("username", [None])[0] if isinstance(user.get("extra"), dict) else None

        path = _build_path(obj_ref, verb, subresource)
        http_method = _VERB_METHOD.get((verb or "").lower(), "GET")

        resource_name = obj_ref.get("resource") if obj_ref else None
        resource_display = f"k8s/{resource_name}" if resource_name else "Kubernetes API Server"

        return LogEvent(
            source_format=LogFormat.K8S_AUDIT,
            timestamp=_ts(ts_raw),
            ip_address=source_ips[0] if source_ips else None,
            user_agent=raw.get("userAgent"),
            http_method=http_method,
            path=path,
            status_code=status_code,
            user_principal_name=username,
            resource_display_name=resource_display,
            failure_reason=failure_reason,
        )
    except Exception as exc:
        logger.debug("Skipping malformed K8s audit event: %s", exc)
        return None


def parse_k8s_audit(content: str) -> list[LogEvent]:
    """Parse Kubernetes audit log (NDJSON or JSON array) into LogEvents."""
    records: list[dict[str, Any]] = []
    stripped = content.strip()

    # Try NDJSON first
    if stripped.startswith("{"):
        for line in stripped.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                if isinstance(obj, dict):
                    records.append(obj)
            except json.JSONDecodeError:
                pass
    else:
        try:
            data = json.loads(stripped)
            if isinstance(data, list):
                records = [r for r in data if isinstance(r, dict)]
            elif isinstance(data, dict):
                records = data.get("items") or [data]
        except json.JSONDecodeError as exc:
            raise ValueError(f"K8s audit parser: invalid JSON — {exc}") from exc

    events = [_parse_event(r) for r in records]
    result = [e for e in events if e is not None]
    logger.info("K8s audit parser: %d/%d events parsed", len(result), len(records))
    return result


class K8sAuditParser(BaseParser):
    format_name = "k8s_audit"

    @classmethod
    def can_parse(cls, content: str, filename: str) -> bool:
        fname_lower = filename.lower()
        if any(x in fname_lower for x in ("kube-audit", "k8s", "kubernetes", "audit_log")):
            stripped = content.strip()
            if stripped.startswith("{") or stripped.startswith("["):
                return True
        head = content.strip()[:3000]
        return (
            '"apiVersion"' in head and "audit.k8s.io" in head
        ) or (
            '"objectRef"' in head and '"verb"' in head
            and '"user"' in head and '"sourceIPs"' in head
        ) or (
            '"objectRef"' in head and '"requestReceivedTimestamp"' in head
        )

    @classmethod
    def parse(cls, content: str, filename: str = "") -> list[LogEvent]:
        return parse_k8s_audit(content)
